### ISSUE TITLE
Is Yeoman a static site generator?

### ISSUE THREAD

**Issue by getsetbro** [pinceladasdaweb/Static-Site-Generators#31]
I think of a static site generator as something that will build the site top nav and footer for you on all of your html pages. Yeoman does not do this. If you add something like angular to your Yeoman app then that will build your site nav but then what you have is a single page app and not a static site of flat html files.

**Comment by xPetrus** [comment]
If you're looking for a static site generator, check out:
https://github.com/assemble/generator-assemble

It's a Yeoman generator for Assemble, built on Grunt.js.
