### ISSUE TITLE
definition of static site generator

### ISSUE THREAD

**Issue by jonschlinkert** [pinceladasdaweb/Static-Site-Generators#39]
I'm curious what definition of "static site generator" this follows. This seems to have taken creative license in a few places, particularly with the words "static" and "site" and "generator". 

I see build systems, blog and wiki frameworks, hosted CMSs, web servers... seems a bit wishy-washy, if not misleading.

**Comment by gld1982ltd** [comment]
I agree. Also, there could be a short description of each service/generator.
